### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by RE-A** [Reichidad/Arujisama#2]
> 이전 레포의 이슈 복사 & 붙여넣기함

## 회원 이메일 인증
1. 회원가입시엔 따로 이메일 인증을 받지 않음.
2. id/pw찾기 기능을 사용하려면 이메일 인증이 필요함.
    - 이메일 인증 시점을 어떻게 할 지 정해야할거 같은데. 나는 가입 때 하는게 맞다고 봄. 가입할 때 '지금 이메일 인증을 하지 않으시면 나중에 ID/PW 못 찾아요'라고 안내하면 된다고 생각하는데. @seolking 
3. 임시적으로 베타버전의 피드백받기와 같은 방식으로 이메일을 인증하지 않은 유저에 대한 알림을 표시함. 이 사항은 언제든지 바뀔 수 있음

## 스탬프 페이지 UX
![image](https://user-images.githubusercontent.com/9834821/64251563-ce300700-cf53-11e9-9231-88787a6f996a.png)

1. [ ]  스탬프 찍기 버튼 변경
2. [ ] 접속 시 안찍은 상태이면 찍은건지 물어보기
3. [x] 당일 메모 수정
4. [ ] 콧코로 말하게 하기
5. [ ] 메모 한번에 보기(번호/시간/메모)
6. [ ] 카드 하나 지우기
7. [ ] 다른 카드 보기
8. [ ] 사용법 설명 페이지
 (1) 이미지 한 장으로 정리
 (2) 처음 로그인 한 회원에겐 한 번 보여주기
9. [ ] id/pw 찾기 페이지

## 백엔드 추가사항
- [ ] 카드 이름 지정하기
- [ ] 카드 하나 지우기
    - 이 카드 기능들은 프론트에도 작업이 필요할 거 같으니 일단은 뒤로 미루겠습니다.
- [ ] 당일 메모 수정
- [ ] https 구축하기
- [ ] 카카오톡 사이트 링크 썸네일/미리보기
   - http://blog.naver.com/PostView.nhn?blogId=byjoo0918&logNo=220890568826
     알고보니 이거 프론트쪽일이네
- [ ] 자동로그인
- [ ] 유저 커스텀 옵션 저장하기
- [ ] id/pw 찾기
